name: Build & Test

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      MRUBY_CONFIG: ci/gcc-clang
      TERM: xterm
      CC: gcc
    steps:
      - uses: actions/checkout@v4
      - name: install gtk
        run: sudo apt-get install -y libgtk-3-dev libtool-bin libncurses5-dev libncursesw5-dev
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: ./build.sh
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: mrbmacs-termbox
          path: mruby/bin/mrbmacs-termbox
      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: Test
        run: faketty ./build.sh test

  macOS:
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      MRUBY_CONFIG: ci/gcc-clang
      CC: clang
    steps:
      - uses: actions/checkout@v4
      - name: install gtk
        run: |
          brew update
          brew install gtk+3 gtk-mac-integration
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: ./build.sh
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: mrbmacs-termbox
          path: mruby/bin/mrbmacs-termbox
      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: Test
        run: faketty ./build.sh test

  Windows-msys2:
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      CC: gcc
      installer-path: '%TMP%\cygwin-setup.exe'
      cygwin-root: C:\cygwin
      package-dir: C:\cygwin-package
      cache-version: v1
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            gcc
            git
            libiconv-devel
            libtool
            make
            pkgconf
            ruby
            mingw-w64-x86_64-pdcurses
            mingw-w64-x86_64-unibilium
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build and test
        run: ./build.sh
