name: Build & Test

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TERM: xterm
      CC: gcc
    steps:
      - uses: actions/checkout@v5
      - name: install gtk
        run: sudo apt-get install -y libgtk-3-dev libtool-bin libncurses5-dev libncursesw5-dev xvfb
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: ./build.sh
      - name: upload mrbmacs-termbox
        uses: actions/upload-artifact@v3
        with:
          name: mrbmacs-termbox
          path: mruby/build/mrbmacs-termbox/bin/mrbmacs-termbox
      - name: upload mrbmacs-curses
        uses: actions/upload-artifact@v3
        with:
          name: mrbmacs-curses
          path: mruby/build/mrbmacs-curses/bin/mrbmacs-curses
      - name: upload mrbmacs-gtk
        uses: actions/upload-artifact@v3
        with:
          name: mrbmacs-gtk
          path: mruby/build/mrbmacs-gtk/bin/mrbmacs-gtk
      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: Test curses
        run: faketty ./build.sh curses test
      - name: Test termbox
        run: faketty ./build.sh termbox test
      - name: Test GTK
        run: xvfb-run ./build.sh gtk test

  macOS:
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      CC: gcc
    steps:
      - uses: actions/checkout@v5
      - name: install gtk
        run: |
          brew update
          brew install gtk+3 gtk-mac-integration
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: ./build.sh
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: mrbmacs-termbox
          path: mruby/bin/mrbmacs-termbox
      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: Test
        run: faketty ./build.sh test

  msys2-termbox:
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      CC: gcc
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v5
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            gcc
            git
            libiconv-devel
            libtool
            make
            pkgconf
            ruby
            mingw-w64-x86_64-pdcurses
            mingw-w64-x86_64-unibilium
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: ./build.sh termbox

  mingw-curses:
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      CC: gcc
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v5
      - name: mingw setup
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ruby
            mingw-w64-x86_64-pdcurses
            mingw-w64-x86_64-unibilium
            mingw-w64-x86_64-libiconv
            mingw-w64-x86_64-libtool
            mingw-w64-x86_64-pkg-config
            git
            make
            patch
            libtool
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: PKG_CONFIG_PATH="" ./build.sh curses
